### ISSUE TITLE
Bitbucket version?

### ISSUE THREAD

**Issue by samselikoff** [HenningM/jstimezonedetect#4]
I found this same library on Bitbucket: https://bitbucket.org/pellepim/jstimezonedetect. Are these the same? We want to install from Bower - is the version on bower correct?

Thanks!

**Comment by Drarok** [comment]
Same here, I want to use bower, but I can't work out which one is the canonical source.

**Comment by HenningM** [comment]
Hi,

The version on bitbucket is the repository of the original author, so that would be the "official" source.
